version: "3"

services: 
  web:
    container_name: exampleapp
    restart: always
    build: .
    ports:
      - "8888:8888" 
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports: 
      - "27018:27017"
    logging:
      driver: none
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80" 
    depends_on:
      - web